[package]
name = "rust-lib"
version = "0.1.0"
authors = ["hoangpq <pquochoang2007@gmail.com>"]
edition = "2018"

[lib]
name = "rust"
crate-type = ["staticlib"]

[dependencies]
sdl2 = "0.27"
log = "0.3"
android_log = "0.1.3"
